{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "healthcare-prediction-api.fullname" . }}-pdb
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "healthcare-prediction-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: pod-disruption-budget
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "healthcare-prediction-api.selectorLabels" . | nindent 6 }}
{{- end }}